# **БФБО-05-23 Баранов Арсений Юрьевич**

1) Импортировать NumPy под именем np:

In [1]:
import numpy as np

2) Напечатать версию и конфигурацию NumPy:

In [2]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

3) Создать вектор (одномерный массив) размера 10, заполненный нулями:

In [3]:
vector_zeros = np.zeros(10)
print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


4) Создать вектор размера 10, заполненный единицами:

In [4]:
vector_ones = np.ones(10)
print(vector_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


5) Создать вектор размера 10, заполненный числом 2.5:

In [5]:
vector_twos_five = np.full(10, 2.5)
print(vector_twos_five)

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


6) Как получить документацию о функции numpy.add из командной строки?

In [8]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

7) Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1:

In [7]:
vector_with_one = np.zeros(10)
vector_with_one[4] = 1
print(vector_with_one)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


8) Создать вектор со значениями от 10 до 49:

In [9]:
vector_range = np.arange(10, 50)
print(vector_range)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


9) Развернуть вектор (первый становится последним):

In [10]:
vector_reversed = vector_range[::-1]
print(vector_reversed)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


10) Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8:

In [11]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


11) Найти индексы ненулевых элементов в [1, 2, 0, 0, 4, 0]:

In [12]:
array = np.array([1, 2, 0, 0, 4, 0])
nonzero_indices = np.nonzero(array)
print(nonzero_indices)

(array([0, 1, 4]),)


12) Создать 3x3 единичную матрицу:

In [13]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


13) Создать массив 3x3x3 со случайными значениями:

In [14]:
array_3x3x3 = np.random.random((3, 3, 3))
print(array_3x3x3)

[[[0.64095161 0.90633331 0.96213843]
  [0.6858537  0.91817207 0.75180808]
  [0.18018531 0.86006881 0.36411972]]

 [[0.23878974 0.01052165 0.55055505]
  [0.83999263 0.82691361 0.4442914 ]
  [0.95253914 0.12196096 0.61485175]]

 [[0.23282963 0.27347306 0.03866442]
  [0.67663587 0.7251901  0.1042723 ]
  [0.9689185  0.82846227 0.53487247]]]


14) Создать массив 10x10 со случайными значениями, найти минимум и максимум:

In [15]:
array_10x10 = np.random.random((10, 10))
print("Минимум:", np.min(array_10x10))
print("Максимум:", np.max(array_10x10))

Минимум: 0.01226536541633172
Максимум: 0.9984785643204414


15) Создать случайный вектор размера 30 и найти среднее значение всех элементов:

In [16]:
vector_30 = np.random.random(30)
print("Среднее значение:", np.mean(vector_30))

Среднее значение: 0.4892780688224409


16) Создать матрицу с 0 внутри, и 1 на границах:

In [17]:
matrix_with_ones_border = np.ones((5, 5))
matrix_with_ones_border[1:-1, 1:-1] = 0
print(matrix_with_ones_border)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


17) Создать 5x5 матрицу с 1,2,3,4 под диагональю:

In [18]:
matrix_with_diagonals = np.diag([1, 2, 3, 4], k=-1)
print(matrix_with_diagonals)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


18) Создать 8x8 матрицу и заполнить её в шахматном порядке:

In [19]:
chessboard = np.zeros((8, 8), dtype=int)
chessboard[1::2, ::2] = 1
chessboard[::2, 1::2] = 1
print(chessboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


19) Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [20]:
array_3d = np.empty((6, 7, 8))
index_100 = np.unravel_index(100, array_3d.shape)
print("Индекс сотого элемента:", index_100)

Индекс сотого элемента: (1, 5, 4)


20) Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile:

In [21]:
tile_pattern = np.array([[0, 1] * 4, [1, 0] * 4] * 4)
print(tile_pattern)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


21) Перемножить матрицы 5x3 и 3x2:

In [22]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print(product_matrix)

[[0.68949599 0.54986753]
 [0.93722355 0.7867999 ]
 [0.90236469 0.3479463 ]
 [1.44743326 1.20496726]
 [0.81483094 0.98354996]]


22) Дан массив, поменять знак у элементов, значения которых между 3 и 8:

In [23]:
array = np.array([1, 4, 6, 2, 8, 3, 7])
array[(array > 3) & (array < 8)] *= -1
print(array)

[ 1 -4 -6  2  8  3 -7]


23) Создать 5x5 матрицу со значениями в строках от 0 до 4:

In [24]:
matrix_rows = np.tile(np.arange(5), (5, 1))
print(matrix_rows)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


24) Есть генератор, сделать с его помощью массив:

In [25]:
def generate_numbers():
    for i in range(10):
        yield i

array_from_generator = np.fromiter(generate_numbers(), dtype=int)
print(array_from_generator)

[0 1 2 3 4 5 6 7 8 9]


25) Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое:

In [26]:
vector_0_to_1 = np.linspace(0, 1, 12)[1:-1]
print(vector_0_to_1)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


26) Отсортировать вектор:

In [27]:
vector = np.random.random(10)
sorted_vector = np.sort(vector)
print(sorted_vector)

[0.1791118  0.33113529 0.4846323  0.64430172 0.73277388 0.76364886
 0.78206317 0.84100977 0.93361833 0.93434244]


27) Проверить, одинаковы ли 2 numpy массива:

In [28]:
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])
are_equal = np.array_equal(array1, array2)
print("Массивы одинаковы:", are_equal)

Массивы одинаковы: True


28) Сделать массив неизменяемым:

In [29]:
array = np.array([1, 2, 3])
array.setflags(write=False)
try:
    array[0] = 10
except ValueError as e:
    print("Ошибка (массив неизменяем):", e)

Ошибка (массив неизменяем): assignment destination is read-only


29) Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную:

In [30]:
cartesian_points = np.random.random((10, 2)) * 10
r = np.sqrt(cartesian_points[:, 0]**2 + cartesian_points[:, 1]**2)
theta = np.arctan2(cartesian_points[:, 1], cartesian_points[:, 0])
polar_coordinates = np.column_stack((r, theta))
print(polar_coordinates)

[[ 8.02161938  1.07538551]
 [ 8.45670396  0.11971823]
 [ 6.75951978  1.34322439]
 [ 8.65689865  0.88143557]
 [ 5.71216213  1.14553341]
 [ 9.1453228   1.37930182]
 [ 5.94484007  0.48756272]
 [ 6.73247463  0.69369613]
 [ 8.88774011  0.42694988]
 [11.32111674  0.80852794]]


30) Заменить максимальный элемент на ноль:

In [31]:
array = np.random.random(10)
array[array.argmax()] = 0
print(array)

[0.12271882 0.03152889 0.25813629 0.27759634 0.17479702 0.
 0.66787117 0.70548378 0.4371307  0.85523763]


31) Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]:

In [32]:
x = np.linspace(0, 1, 5)
y = np.linspace(0, 1, 5)
X, Y = np.meshgrid(x, y)
structured_array = np.zeros(X.shape, dtype=[('x', float), ('y', float)])
structured_array['x'] = X
structured_array['y'] = Y
print(structured_array)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


32) Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj)):

In [33]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
X, Y = np.meshgrid(x, y)
C = 1 / (X - Y.T)
print(C)

[[-0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333]
 [-0.33333333 -0.33333333 -0.33333333]]


33) Найти минимальное и максимальное значение, принимаемое каждым числовым типом NumPy:

In [44]:
# Для целочисленных типов
print("Минимальное значение int8:", np.iinfo(np.int8).min)
print("Максимальное значение int8:", np.iinfo(np.int8).max)
print("Минимальное значение int16:", np.iinfo(np.int16).min)
print("Максимальное значение int16:", np.iinfo(np.int16).max)
print("Минимальное значение int32:", np.iinfo(np.int32).min)
print("Максимальное значение int32:", np.iinfo(np.int32).max)
print("Минимальное значение int64:", np.iinfo(np.int64).min)
print("Максимальное значение int64:", np.iinfo(np.int64).max)

# Для чисел с плавающей запятой
print("Минимальное значение float32:", np.finfo(np.float32).min)
print("Максимальное значение float32:", np.finfo(np.float32).max)
print("Минимальное значение float64:", np.finfo(np.float64).min)
print("Максимальное значение float64:", np.finfo(np.float64).max)

Минимальное значение int8: -128
Максимальное значение int8: 127
Минимальное значение int16: -32768
Максимальное значение int16: 32767
Минимальное значение int32: -2147483648
Максимальное значение int32: 2147483647
Минимальное значение int64: -9223372036854775808
Максимальное значение int64: 9223372036854775807
Минимальное значение float32: -3.4028235e+38
Максимальное значение float32: 3.4028235e+38
Минимальное значение float64: -1.7976931348623157e+308
Максимальное значение float64: 1.7976931348623157e+308


34) Напечатать все значения в массиве:

In [37]:
array = np.array([1, 2, 3, 4, 5])
np.set_printoptions(threshold=np.inf)
print(array)

[1 2 3 4 5]


35) Найти ближайшее к заданному значению число в заданном массиве:

In [38]:
array = np.array([1, 3, 5, 7, 9])
value = 6
closest_value = array[np.abs(array - value).argmin()]
print("Ближайшее значение:", closest_value)

Ближайшее значение: 5


36) Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b):

In [39]:
structured_array = np.zeros((3,), dtype=[('coord', float, (2,)), ('color', float, (3,))])
structured_array['coord'] = [(0, 0), (1, 1), (2, 2)]
structured_array['color'] = [(1, 0, 0), (0, 1, 0), (0, 0, 1)]
print(structured_array)

[([0., 0.], [1., 0., 0.]) ([1., 1.], [0., 1., 0.])
 ([2., 2.], [0., 0., 1.])]


37) Дан массив (100,2) координат, найти расстояние от каждой точки до каждой:

In [40]:
coordinates = np.random.random((100, 2))
distances = np.sqrt(((coordinates[:, np.newaxis, :] - coordinates[np.newaxis, :, :]) ** 2).sum(axis=2))
print(distances)

[[0.         0.22535198 0.45706868 0.39440201 0.57438111 0.76732234
  0.77681449 0.64752755 0.87723044 0.64375016 0.40924687 0.20465442
  0.81768079 0.84986162 0.51306691 0.74605308 0.62543918 0.68664068
  0.56464626 0.13431878 0.17448945 0.76347733 0.18615013 0.77710388
  0.27467648 0.78520065 0.78272431 0.78893029 0.84856206 0.37541352
  0.20527225 0.83893462 0.48415075 0.75917911 0.36415162 0.91693413
  0.34029884 0.38605946 0.24757743 0.79893418 0.25926465 0.82040611
  0.72686422 0.8542133  0.39196125 0.92537315 0.24895768 0.63979973
  0.31273979 0.63126123 0.89840542 0.49300072 0.0977373  0.6863005
  0.88909168 0.96929565 0.50294477 0.45500578 0.50471722 0.74208368
  0.32234105 0.77605673 0.84635102 0.45724491 0.41006994 0.27180297
  0.26990525 0.68856005 0.5769481  0.84324243 1.11254811 0.92677765
  0.98735975 0.44046257 0.63656339 1.16765094 0.20462485 0.7867606
  0.56372955 0.78654963 0.5483663  0.8733741  0.08993297 0.77840347
  0.24655298 0.44670621 0.56797518 0.43658866 0.23

38) Преобразовать массив из float в int:

In [41]:
float_array = np.array([1.5, 2.7, 3.9])
int_array = float_array.astype(int)
print(int_array)

[1 2 3]


39) Каков эквивалент функции enumerate для NumPy массивов?

In [42]:
array = np.array(['a', 'b', 'c'])
for index, value in np.ndenumerate(array):
    print(f"Индекс: {index}, Значение: {value}")

Индекс: (0,), Значение: a
Индекс: (1,), Значение: b
Индекс: (2,), Значение: c


40) Сформировать 2D массив с распределением Гаусса:

In [45]:
mean = 0
std_dev = 1
size = (5, 5)  # Размер массива
gaussian_array = np.random.normal(mean, std_dev, size)
print(gaussian_array)

[[ 0.57602378  0.40807938  0.47072417  0.78529067  1.86687034]
 [ 0.16008754 -0.27072695 -0.03703132 -2.56944067  0.85299128]
 [-1.26601513 -1.58447803  0.07088048 -0.6069549  -0.31117357]
 [ 1.68074019  0.37421678  0.58326134 -0.53353396  1.06878012]
 [ 0.61430135 -0.38851107  1.09132451  1.48989145 -0.11195398]]


41) Случайно расположить p элементов в 2D массив:

In [46]:
rows, cols = 5, 5
p = 10
array = np.zeros((rows, cols), dtype=int)
indices = np.random.choice(rows * cols, p, replace=False)
array.ravel()[indices] = 1
print(array)

[[0 1 0 0 0]
 [1 1 0 1 0]
 [1 1 0 0 0]
 [0 0 1 0 0]
 [0 0 1 1 1]]


42) Отнять среднее из каждой строки в матрице:

In [47]:
matrix = np.random.random((4, 4))
mean_per_row = matrix.mean(axis=1, keepdims=True)
centered_matrix = matrix - mean_per_row
print(centered_matrix)

[[-0.15583006  0.20181921 -0.15969644  0.11370728]
 [ 0.37506049 -0.11302012  0.12122732 -0.3832677 ]
 [-0.31323745 -0.14600553  0.26484525  0.19439773]
 [-0.24918695  0.43761876 -0.01599545 -0.17243637]]


43) Отсортировать матрицу по n-ому столбцу:

In [48]:
n = 2
matrix = np.random.random((4, 4))
sorted_matrix = matrix[matrix[:, n].argsort()]
print(sorted_matrix)

[[0.79767324 0.06550377 0.42669068 0.99170087]
 [0.24464209 0.65160934 0.57211064 0.24604376]
 [0.55634195 0.25270372 0.80265723 0.86911435]
 [0.15755812 0.41536115 0.84733354 0.72488293]]


44) Определить, есть ли в 2D массиве нулевые столбцы:

In [49]:
matrix = np.random.random((4, 4))
zero_columns = np.any(matrix == 0, axis=0)
has_zero_columns = np.any(zero_columns)
print("Есть нулевые столбцы:", has_zero_columns)

Есть нулевые столбцы: False


45) Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами):

In [51]:
array = np.array([0, 0, 0, 0, 0])
indices = np.array([1, 2, 2, 4])
np.add.at(array, indices, 1)
print(array)

[0 1 2 0 1]


46) Дан массив (w, h, 3) (картинка) dtype=ubyte, посчитать количество различных цветов:

In [52]:
image = np.random.randint(0, 256, (4, 4, 3), dtype=np.uint8)
unique_colors = np.unique(image.reshape(-1, 3), axis=0)
num_unique_colors = unique_colors.shape[0]
print("Количество различных цветов:", num_unique_colors)

Количество различных цветов: 16


47) Дан четырехмерный массив, посчитать сумму по последним двум осям:

In [53]:
array_4d = np.random.random((3, 4, 5, 6))
sum_last_two_axes = np.sum(array_4d, axis=(-2, -1))
print(sum_last_two_axes)

[[17.8322297  17.87042392 13.49296085 16.69539756]
 [13.78843278 13.32432311 16.19079699 14.55896749]
 [15.7801745  16.11494776 14.24384678 14.41125301]]


48) Найти диагональные элементы произведения матриц:

In [54]:
matrix1 = np.random.random((3, 3))
matrix2 = np.random.random((3, 3))
product = np.dot(matrix1, matrix2)
diagonal_elements = np.diag(product)
print(diagonal_elements)

[0.52084125 1.44819422 1.05490557]


49) Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением:

In [55]:
vector = np.array([1, 2, 3, 4, 5])
new_vector = np.zeros(len(vector) * 4 - 3)
new_vector[::4] = vector
print(new_vector)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


50) Поменять 2 строки в матрице:

In [56]:
matrix = np.random.random((4, 4))
matrix[[0, 1]] = matrix[[1, 0]]
print(matrix)

[[0.63596898 0.19024221 0.18530592 0.81560676]
 [0.03668534 0.17702413 0.24302098 0.60109567]
 [0.51193091 0.33312892 0.10243651 0.91798506]
 [0.25084554 0.51179484 0.52694624 0.74115815]]


51) Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники:

In [57]:
triangles = np.array([
    [0, 1, 2],
    [1, 2, 3],
    [2, 3, 4],
    [3, 4, 5],
    [4, 5, 6],
    [5, 6, 7],
    [6, 7, 8],
    [7, 8, 9],
    [8, 9, 0],
    [9, 0, 1]
])

edges = set()
for triangle in triangles:
    edges.update({tuple(sorted((triangle[i], triangle[j]))) for i in range(3) for j in range(i + 1, 3)})
print("Уникальные отрезки:", edges)


Уникальные отрезки: {(0, 1), (2, 4), (1, 2), (3, 4), (4, 6), (5, 7), (7, 9), (6, 7), (0, 2), (8, 9), (0, 8), (1, 3), (1, 9), (3, 5), (6, 8), (0, 9), (2, 3), (4, 5), (5, 6), (7, 8)}


52) Дан массив C; создать массив A, что np.bincount(A) == C:

In [58]:
C = np.array([0, 2, 1, 3])
A = np.repeat(np.arange(len(C)), C)
print("Массив A:", A)
print("np.bincount(A):", np.bincount(A))

Массив A: [1 1 2 3 3 3]
np.bincount(A): [0 2 1 3]


53) Посчитать среднее, используя плавающее окно:

In [59]:
from scipy.ndimage import uniform_filter1d

data = np.random.random(10)
window_size = 3
moving_average = uniform_filter1d(data, size=window_size)
print("Скользящее среднее:", moving_average)

Скользящее среднее: [0.76418898 0.83255996 0.7290156  0.71089913 0.69022745 0.8044968
 0.80444066 0.7742875  0.66427421 0.58107647]


54) Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1])):

In [60]:
Z = np.array([1, 2, 3, 4, 5])
matrix_from_vector = np.array([Z[i:i + 3] for i in range(len(Z) - 2)])
print(matrix_from_vector)

[[1 2 3]
 [2 3 4]
 [3 4 5]]


55) Инвертировать булево значение, или поменять знак у числового массива без создания нового:

In [61]:
bool_array = np.array([True, False, True])
bool_array[:] = ~bool_array
print(bool_array)

numeric_array = np.array([1, -2, 3])
numeric_array[:] = -numeric_array
print(numeric_array)

[False  True False]
[-1  2 -3]


56) Рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку p, как вычислить расстояние от p до каждой линии (P0[i],P1[i]):

In [62]:
from numpy.linalg import norm

def point_to_line_distance(P0, P1, p):
    line_vec = P1 - P0
    point_vec = p - P0
    line_length_squared = np.sum(line_vec**2)
    if line_length_squared == 0:
        return np.linalg.norm(p - P0)
    t = np.clip(np.dot(point_vec, line_vec) / line_length_squared, 0, 1)
    projection = P0 + t * line_vec
    return np.linalg.norm(p - projection)

P0 = np.array([[1, 1], [2, 2], [3, 3]])
P1 = np.array([[4, 4], [5, 5], [6, 6]])
p = np.array([3, 2])
distances = np.array([point_to_line_distance(P0[i], P1[i], p) for i in range(P0.shape[0])])
print(distances)

[0.70710678 0.70710678 1.        ]


57) Дан массив. Написать функцию, выделяющую часть массива фиксированного размера с центром в данном элементе (дополненное значением fill если необходимо):

In [63]:
def extract_patch(array, center, size, fill_value=0):
    r, c = center
    h, w = size
    pad_h = h // 2
    pad_w = w // 2
    padded_array = np.pad(array, ((pad_h, pad_h), (pad_w, pad_w)), constant_values=fill_value)
    return padded_array[r:r+h, c:c+w]

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])
center = (2, 2)
size = (3, 3)
print(extract_patch(array, center, size, fill_value=0))


[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


58) Посчитать ранг матрицы:

In [64]:
matrix = np.random.random((4, 4))
rank = np.linalg.matrix_rank(matrix)
print("Ранг матрицы:", rank)

Ранг матрицы: 4


59) Найти наиболее частое значение в массиве:

In [65]:
array = np.array([1, 2, 3, 1, 2, 1])
values, counts = np.unique(array, return_counts=True)
most_frequent_value = values[counts.argmax()]
print("Наиболее частое значение:", most_frequent_value)

Наиболее частое значение: 1


60) Извлечь все смежные 3x3 блоки из 10x10 матрицы:

In [66]:
from skimage.util import view_as_windows

matrix = np.random.random((10, 10))
blocks = view_as_windows(matrix, (3, 3))
print(blocks.shape)  # Ожидается (8, 8, 3, 3)
print(blocks)

(8, 8, 3, 3)
[[[[0.2336537  0.18875381 0.01457161]
   [0.67318784 0.06048159 0.14037673]
   [0.05228693 0.20261626 0.85073413]]

  [[0.18875381 0.01457161 0.28109333]
   [0.06048159 0.14037673 0.71109277]
   [0.20261626 0.85073413 0.3504378 ]]

  [[0.01457161 0.28109333 0.18311234]
   [0.14037673 0.71109277 0.38643428]
   [0.85073413 0.3504378  0.28448858]]

  [[0.28109333 0.18311234 0.55879131]
   [0.71109277 0.38643428 0.53845834]
   [0.3504378  0.28448858 0.68235645]]

  [[0.18311234 0.55879131 0.99800628]
   [0.38643428 0.53845834 0.18754322]
   [0.28448858 0.68235645 0.26080733]]

  [[0.55879131 0.99800628 0.62187162]
   [0.53845834 0.18754322 0.70408813]
   [0.68235645 0.26080733 0.94604425]]

  [[0.99800628 0.62187162 0.88651886]
   [0.18754322 0.70408813 0.80750045]
   [0.26080733 0.94604425 0.64278868]]

  [[0.62187162 0.88651886 0.69595333]
   [0.70408813 0.80750045 0.51200279]
   [0.94604425 0.64278868 0.83527762]]]


 [[[0.67318784 0.06048159 0.14037673]
   [0.05228693 0.20

61) Создать подкласс симметричных 2D массивов (Z[i,j] == Z[j,i]):

In [67]:
class SymmetricMatrix(np.ndarray):
    def __new__(cls, shape):
        obj = np.zeros(shape, dtype=float).view(cls)
        return obj

    def __array_finalize__(self, obj):
        if obj is None: return
        if self.shape[0] != self.shape[1]:
            raise ValueError("Матрица должна быть квадратной")

    def __setitem__(self, key, value):
        super().__setitem__(key, value)
        if isinstance(key, tuple):
            i, j = key
            self[j, i] = value

matrix = SymmetricMatrix((4, 4))
matrix[1, 2] = 5
print(matrix)

RecursionError: maximum recursion depth exceeded while calling a Python object

62) Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1)):

In [68]:
n = 4
p = 3
matrices = [np.random.random((n, n)) for _ in range(p)]
vectors = [np.random.random((n, 1)) for _ in range(p)]

result = sum(np.dot(m, v) for m, v in zip(matrices, vectors))
print(result)

[[2.07458219]
 [1.93869466]
 [3.20349476]
 [1.88870495]]


63) Дан массив 16x16, посчитать сумму по блокам 4x4:

In [69]:
from skimage.measure import block_reduce

array = np.random.random((16, 16))
reduced_sum = block_reduce(array, (4, 4), np.sum)
print(reduced_sum)

[[7.69455818 7.68634023 7.49796702 8.10259498]
 [9.72401327 5.78571208 8.89416164 7.90677157]
 [8.93974424 6.15707165 8.73973661 7.38456107]
 [8.31453529 6.89994261 8.02209891 6.8010268 ]]


64) Написать игру "жизнь":

In [70]:
def game_of_life(board, iterations=1):
    from scipy.ndimage import convolve

    kernel = np.array([[0, 1, 0],
                       [1, 0, 1],
                       [0, 1, 0]])

    for _ in range(iterations):
        neighbors = convolve(board.astype(int), kernel, mode='constant', cval=0.0)
        board = (neighbors == 3) | ((board == 1) & (neighbors == 2))
    return board

initial_board = np.random.choice([0, 1], size=(5, 5))
print("Initial Board:\n", initial_board)
evolved_board = game_of_life(initial_board, iterations=1)
print("Evolved Board:\n", evolved_board)

Initial Board:
 [[0 0 1 0 1]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 1 0]]
Evolved Board:
 [[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]


65) Найти n наибольших значений в массиве:

In [71]:
array = np.random.random(10)
n = 3
largest_values = np.partition(array, -n)[-n:]
print("Наибольшие значения:", largest_values)

Наибольшие значения: [0.85071465 0.95128152 0.99963148]


66) Построить прямое произведение массивов (все комбинации с каждым элементом):

In [72]:
A = np.array([1, 2])
B = np.array([3, 4])
C = np.array(np.meshgrid(A, B)).T.reshape(-1, 2)
print("Прямое произведение:", C)

Прямое произведение: [[1 3]
 [1 4]
 [2 3]
 [2 4]]


67) Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B:

In [73]:
A = np.random.randint(0, 10, (8, 3))
B = np.random.randint(0, 10, (2, 2))

def contains_elements(row, elements):
    return all(elem in row for elem in elements)

matching_rows = [row for row in A if any(contains_elements(row, b_row) for b_row in B)]
print("Строки в A, содержащие элементы из каждой строки в B:\n", matching_rows)

Строки в A, содержащие элементы из каждой строки в B:
 [array([3, 2, 1])]


68) Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3]):

In [74]:
matrix = np.random.randint(0, 5, (10, 3))
unique_rows = matrix[np.any(np.diff(matrix, axis=1) != 0, axis=1)]
print("Строки с неравными значениями:\n", unique_rows)

Строки с неравными значениями:
 [[2 4 0]
 [1 0 4]
 [3 0 1]
 [4 3 1]
 [1 2 0]
 [2 3 0]
 [2 3 3]
 [3 3 1]
 [2 4 0]
 [4 0 0]]


69) Преобразовать вектор чисел в матрицу бинарных представлений:

In [75]:
vector = np.array([1, 2, 3, 4])
binary_matrix = np.array([list(np.binary_repr(x, width=4)) for x in vector], dtype=int)
print("Матрица бинарных представлений:\n", binary_matrix)

Матрица бинарных представлений:
 [[0 0 0 1]
 [0 0 1 0]
 [0 0 1 1]
 [0 1 0 0]]


70) Дан двумерный массив. Найти все различные строки:

In [76]:
array = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3], [7, 8, 9]])
unique_rows = np.unique(array, axis=0)
print("Все различные строки:\n", unique_rows)

Все различные строки:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


71) Даны векторы A и B, написать einsum эквиваленты функций inner, outer, sum и mul:


In [77]:
A = np.array([1, 2, 3])
B = np.array([4, 5, 6])

# inner
inner_product = np.einsum('i,i->', A, B)
print("Inner product:", inner_product)

# outer
outer_product = np.einsum('i,j->ij', A, B)
print("Outer product:\n", outer_product)

# sum
array = np.array([[1, 2], [3, 4]])
sum_all = np.einsum('ij->', array)
print("Sum:", sum_all)

# mul (element-wise multiplication)
elementwise_product = np.einsum('i,i->i', A, B)
print("Element-wise multiplication:", elementwise_product)

Inner product: 32
Outer product:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
Sum: 10
Element-wise multiplication: [ 4 10 18]


### Рандомайзер

In [7]:
import random as r
a = [r.randint(20, 71) for _ in range(10)]
print(sorted(a))

[20, 23, 24, 28, 29, 34, 34, 43, 63, 71]
